### ISSUE TITLE
Dalmatinerdb installation

### ISSUE THREAD

**Issue by mohsalsaleem** [dalmatinerdb/dalmatinerdb#101]
I'm new to dalmatinerdb
I tried building dalmatinerdb as mentioned in the documentation at https://dalmatiner.readme.io/docs/ddb-installation.
After make all rel was completed, the next command was 
`cp -r rel/dalmatinerdb $TARGET_DIRECTORY`
There was no folder named dalmatinerdb as mentions in the doc inside rel folder.
I found a new release created inside of _build/prod directory named ddb. I created the config file and then tried to start ddb using the command 
`./bin/ddb start`

I'm getting the following error

vm.args needs to have a -name parameter.
  -sname is not supported.

Besides, the steps in the documention does not seem to match with the files and folders that are being created.

**Comment by Licenser** [comment]
have you done the configuration part? https://dalmatiner.readme.io/docs/ddb-configuration

**Comment by nginn** [comment]
@mohsalsaleem the steps are like this:
1) `make all rel`
2) you get the directory `_build/prod/rel/ddb` -- that's where all the files you need are 
3) you create directory `/data/dalmatinerdb` and copy everything from `_build/prod/rel/ddb` there
4) you don't forget to rename configuration file, for example:
```
cp /data/dalmatinerdb/etc/dalmatinerdb.conf.example /data/dalmatinerdb/etc/dalmatinerdb.conf
```
-- or else you'll get the error about -name parameter. It's being parsed from the file `/data/dalmatinerdb/etc/dalmatinerdb.conf` and when this file doesn't exist... well, the running scripts don't get any -name parameter for Erlang virtual machine
5. you don't forget to fix ownership of all files and directories inside `/data/dalmatinerdb` so that process can create logfiles

**Comment by mohsalsaleem** [comment]
Thanks. I have solved it. BTW, the docs at https://dalmatiner.readme.io/docs/ddb-installation need to be updated.
