### ISSUE TITLE
Dalmatiner db data structure

### ISSUE THREAD

**Issue by jestervoo** [dalmatinerdb/dalmatinerdb#110]
My question is about data structure i don't find any information(about my case) in docs.
For example i want to store data like:
timestamp| tag1| tag2|tag3|tag4|tag5| value
2017-01-01| cpu| central| tokyo| something|something| 10
...
Also i want to find average value grouped by tag1/tag2 for some period.
Is it possible case for Dalmatiner DB? How i can do this?
Maybe you could give me link on documentation or something else.

Thanks in advance.

**Comment by Licenser** [comment]
First of I'd start with this part of the docs:
https://dalmatiner.readme.io/docs/tradeoffs-design

In very simplified terms metrics are statically indexed arrays for DalmatinerDB.

Instead of tag dalmatinerdb uses metrics and dimensions (key value pairs) which are more expressive and allow for 'simulating' tags by either using tag1=cpu or cpu="".

Alternatively a simple resource path works well if you always have the same number of tag, however you loose the option of aggregating and more complex queries.

DalmatinerDB does not enforce a special protocol, instead it has a ingres proxy that can use different systems your example above would look in them as follows:

# Graphite
this system has no dimensional support
```
cpu.central.tokyo.something.something 10 2017-01-01....
cpu.central.berlin.something.something 15 2017-01-01....
```

#  InfluxDB
This system does support dimensions
```
cpu,dc=tokyo,grouping=central,something=somethingelse value=10 1434055562000010000
cpu,dc=berlin,grouping=central,something=somethingelse value=15 1434055562000010000
```

# OpenTSDB
This system too supports dimensions

```
cpu dc=tokyo,grouping=centrall,something=somethingelse        1356998400  10
cpu dc=berlin,grouping=centrall,something=somethingelse        1356998400  15
```

# Recording

There are already a vast number of tools that can be used to record metrics to the protocol above so you probably won't need to re-invent the wheel here

**Comment by jestervoo** [comment]
Thank you for your reply, it helped me a lot.
