### ISSUE TITLE
make all fails on CentOS 7

### ISSUE THREAD

**Issue by rubenk** [dalmatinerdb/dalmatinerdb#2]
Hi, I'm very interested in dalmatinerdb, and trying to get it to work on CentOS 7.

I just did a checkout, and make all deps rel.

This fails with
```
==> dalmatiner_db (compile)
Compiled src/dalmatiner_write_fsm_sup.erl
Compiled src/dalmatiner_db_sup.erl
Compiled src/dalmatiner_coverage_fsm.erl
Compiled src/dalmatiner_db_udp_sup.erl
Compiled src/dalmatiner_coverage_fsm_sup.erl
Compiled src/dalmatiner_write_fsm.erl
/root/dalmatinerdb/apps/dalmatiner_db/src/dalmatiner_tcp.erl:21: undefined macro 'KEEPALIVE'
/root/dalmatinerdb/apps/dalmatiner_db/src/dalmatiner_tcp.erl:16: function loop/2 undefined
ERROR: compile failed while processing /root/dalmatinerdb/apps/dalmatiner_db: rebar_abort
make: *** [compile] Error 1
```

**Comment by Licenser** [comment]
Hi Ruben,
can you checkout the dev branch it should work. I generally follows the same methodology for branches as I do with Project FiFo:
* test - for active development, might include broken commits
* dev - for development releases, should build and mostly work
* master - for versioned releases

Now with DalmatinerDB it's in the odd situation that there was no versioned release yet but I could not figure out a way not to have a master branch so master is some derelict from before I branched dev and test off.

Generally using master would be the correct thing, sadly so due to not having a full release yet you'll have to stick with dev :)

Cheers,
Heinz

**Comment by rubenk** [comment]
Hi Heinz,

This was the dev branch, when you clone git@github.com:dalmatinerdb/dalmatinerdb.git origin/HEAD points to dev.

Kind regards,

Ruben

**Comment by Licenser** [comment]
Yea I changed the default branch to dev for the time being, will go back to master once the first versioned release is out however there are some things to do until then :).

Come by the IRC channel if you like to (#dalmatinerdb on freenode) I'm curious how it goes on CentOS! So far I've only run it on SmartOS so that is a new environment :)

**Comment by rubenk** [comment]
Ah, yes, I did a new checkout and it works. Now let me try to get it running :)
