### ISSUE TITLE
non_negative_derivative(<metric>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#31]
To plot rates without odd negative values when counters reset

**Comment by sacreman** [comment]
These are quite popular in InfluxDB when used for DevOps things like network counters since they can get reset and then you end up with odd negative spikes which ruin dashboard widgets. I have some crazy code in some of my plugins to prevent this happening, but not all data comes from plugins. We will probably end up wanting to calculate rate from SNMP data at some stage which will get streamed in.

I guess if you can nest derivative inside an abs() this wouldn't be required.

**Comment by Licenser** [comment]
yea this sounds very sensible to have

**Comment by Licenser** [comment]
Thinking more about this I am in favour for having a `min_value(<metric>, <number>)` and a `max_value(<metric>, <number>)` function. They are more general and `non_negative_derivate` could be written as `min_value(derivate(<metric>), 0)`

**Comment by Licenser** [comment]
This can be replaced by #73.
