### ISSUE TITLE
count(?)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#41]

**Comment by sacreman** [comment]
This is possibly badly named since count() could mean number of points in a series. Which might be useful, but wasn't the aim.

This one was more around alerting. For a given set of dimensions reply with the number of metric paths that have values in the range. This would allow us to alert off ephemeral data sources like containers where we'd like to alert if 'less than X' are returning data for a metric path.

So the same as https://support.signalfx.com/hc/en-us/articles/203761489-SignalFlow-analytics-reference-guide#count

**Comment by Licenser** [comment]
hmmmm this will require some thinking

**Comment by Licenser** [comment]
this is more generally implemented with `count_above` and `sum` the functions are more generic but would allow for the same result: `count(<some metretrics>)` = `sum(count_above(<metric>, 0, 1s))`
