### ISSUE TITLE
sort_desc(?)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#46]

**Comment by sacreman** [comment]
We have widget popovers and legends in the app which would benefit from returning query results with a set ordering so that the web client doesn't need to do it.

This would work similarly to the prometheus sort function where it would return ordered metrics by value.

https://prometheus.io/docs/querying/functions/#sort()

**Comment by Licenser** [comment]
Oh this is for sorting based on 'names' for the order of returned metrics in the result set not for the values? that makes more sense

**Comment by Licenser** [comment]
I'm convinced sorting by names is a lot easier to do at the time the query is drawn, the required code for that is about 1 line, for adding logic of sorting into the query engine it's orders of magnitude more complicated. Also queries are sorted by the order they are written (same as for SQL) changing that sorting would seem wrong.
