### ISSUE TITLE
Support wildcards in lookup queries (with WHERE clause)

### ISSUE THREAD

**Issue by szarsti** [dalmatinerdb/dalmatinerdb#71]
We need it to catch up with feature set of competing products. Quoting Steven:

> you can do wildcards and dimensions in both prometheus and influxdb. it's kind of a basic requirement
> 
> flexibility is having both work separately and together
> 
> we need the proper wildcard in the metric path too at some point. i.e. not just a * taking the whole slot. but a regex in there with it too

**Comment by Licenser** [comment]
This is not correct, I don't know about influx but you can not use wildcards in prometheus. They do not even have a concept of a metric path to start with, their 'path' is just a string no concept of seperation.

Two distinct metrics measure two distinct things (and in nearly all cases have different units!) so a glob over multiple metrics makes little sense.

If this is a problem that the real issue is the schema that was choosen, if a * is in a metric path then that element should have been a dimension.

Putting a glob in a metric is the logic equivalent of asking someone to add all the top speeds and colors of the cars driven in your company.

**Comment by sacreman** [comment]
The problem is that we need to support not just Prometheus format data but also Nagios performance data and StatsD data in the same Grafana plugin.

One customer upgrading from 2.6 Grafana to 3.0 Grafana has a StatsD server pushing lots of metrics into a bucket. With the current query editor I do:

FROM <account> SELECT stats.web.service.*.success

I'd expect that to return every metric path that met that regex in the entire account.

Then to narrow it down to just a single server it would seem logical to do:

FROM <account> WHERE dl:source = statsd_server1 SELECT stats.web.service.*.success

If we were simply supporting dimensional data in Grafana it would be a bit easier. Nagios / Grafana non-dimensional are here to stay though and the only other option is encoding the bucket in the metric path which looks very odd when dealing with metrics with dimensions.

I've had a chat to @davecromberge about maybe fluffing it in the UI for non-dimensional data. So you can do * in the metric path for StatsD data and then when you use WHERE on dl:source = it converts the query over to specifying the bucket.

The problem with all of this is that when you provide a UI people expect it to work in all ways possible. As soon as you say X works in Y case but not with Z people do it that way and then raise a bug ticket. For user simplicity it would be best if *'s could be used anywhere in the metric path both with and without a where clause.

**Comment by Licenser** [comment]
As it violates the general idea of dimensions this will not be supported in dalmatiner directly, but we've found a solution that allows to build this ontop of the existing protocols.
